### ISSUE TITLE
CUDA Version

### ISSUE THREAD

**Issue by zhong-yi-lin** [farewellthree/PPLLaVA#1]
I am trying to run the scripts with CUDA 11.7 installed, but I keep getting the error :
RuntimeError: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver.

So, what's the right version? Thank you.

**Comment by farewellthree** [comment]
Hi, torch>=2.0 requires CUDA>=11.8, and the newest qwen model seems requiring torch>=2.1.2
