### ISSUE TITLE
Question about Activitynet dataset preparation

### ISSUE THREAD

**Issue by Parsifal133** [farewellthree/PPLLaVA#3]
Hi! Thanks for the great work and open source code.

I noticed that Activitynet's video frame data is used for inference, as shown in the code below.

[frame='/Path/to/video_chatgpt/activitynet_frames.json'](https://github.com/farewellthree/PPLLaVA/blob/main/ppllava/test/qabench/utils.py#L32)

It involves a json file about the frames. I don't know how to find this file.

I checked the relevant git repos, such as [St-llm](https://github.com/TencentARC/ST-LLM), [video-chatgpt,](https://github.com/mbzuai-oryx/Video-ChatGPT) and [activitynet-qa,](https://github.com/MILVLG/activitynet-qa/tree/master/dataset) but I didn't find relevant information.
Can you please share how to get this file and how to use Activitynet for model evaluation?

**Comment by farewellthree** [comment]
Hello. Apologies for the confusion, the activitynet_frames.json is actually not necessary, and we have corrected the code. Additionally, our ActivityNet dataset consists of pre-extracted raw frames. If your ActivityNet is in raw video format, you can modify the code similarly to how it is done for MSR-VTT or MSVD.

**Comment by Parsifal133** [comment]
Thanks for your reply！
I can now evaluate the model on Activitynet dataset, based on the latest code you provided.
