### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by zhuqiangLu** [farewellthree/PPLLaVA#6]
Hi, may I ask what dataset is used for training

**Comment by farewellthree** [comment]
Hi, all training settings can be found in the trainval.md as well as in the paper

**Comment by zhuqiangLu** [comment]
Cheers, may I ask why these dataset specifically? 
I did a quick math and realized the dataset is quite large. I was thinking to reproduce the result with LORA, but considering the size of the dataset, it may take a while. 
My plan is to train PPLLaVA on a smaller dataset as a proxy. If you have tried training on a smaller dataset, please let me know which dataset it is and how PPLLaVA performs. 

Best

**Comment by zhuqiangLu** [comment]
Never mind my silly questions. I just found the training section in the paper. 
Closing this issue.
