### ISSUE TITLE
Question about DPO

### ISSUE THREAD

**Issue by Parsifal133** [farewellthree/PPLLaVA#7]
Hi, @farewellthree !
I am interested in the DPO part of PPLLaVA. I tried to run the DPO code but got this error:
`Traceback (most recent call last):
  File "/work/ppllava/ppllava/train/train_dpo.py", line 44, in <module>
    from ppllava.conversation import llavahound_conversation as conversation_lib
ImportError: cannot import name 'llavahound_conversation' from 'ppllava.conversation' (/work/ppllava/ppllava/conversation/__init__.py)
`
I have some questions regarding DPO training data and would appreciate it if you could take the time to walk me through it:

a) where can the dataset used by DPO be found?
I tried to explore this problem myself by consulting the DPO config file and running the DPO training code directly. 
The config file involves `llava-hound-300k` and `sft_dpo_17k.jsonl`, which I will search and find further, but DPO training does not seem to be able to execute because of the error mentioned above;

b) your paper mentioned that DPO was performed with reference to LLAVA-HOUND. I quickly checked the code for DPO training in ppllava. It seems that GPT4V is not involved, but the offline dataset is used. Is that right? (This question is actually similar to question 1)

**Comment by farewellthree** [comment]
Hi, this bug has just been fixed. json file can be found [here](https://huggingface.co/datasets/ShareGPTVideo/train_video_and_instruction/resolve/main/video_instruction/train/dpo/sft_dpo_17k.jsonl?download=true). Videos can be found [here](https://huggingface.co/datasets/ShareGPTVideo/train_video_and_instruction/tree/main/train_300k)

**Comment by Parsifal133** [comment]
Thanks for your reply, my problem should have been solved

Hope you have a nice day
